### ISSUE TITLE
(Incomplete) No code in submission

### ISSUE THREAD

**Issue by CharlesDLandau** [wickram/intro-data-capstone-biodiversity#1]
Please resubmit your project when it has been completed - there is no code in this repo, only a presentation.

**Comment by wickram** [comment]
Hi,

I did the project in code academy, should I need to copy and paste the code?

Regards,
Wicky

**Comment by CharlesDLandau** [comment]
No it should just work. Submit a bug report at the bottom of the project
page and say you are blocked from proceeding to code review.

Thanks,
Charles
