### ISSUE TITLE
Great use of variable naming conventions 

### ISSUE THREAD

**Issue by Caealana** [wickram/intro-data-capstone-biodiversity#7]
https://github.com/wickram/intro-data-capstone-biodiversity/blob/84afeeeeb7ab2d86e0e9d68a8b610416e95304ee/Code%20Academy/bio-diversity-code#L7-L19

Great job! Your variables are aptly named here. Your variable names are descriptive and specific as to what kind of information is being stored. 

One suggestion: You could comment this chunk of code with details about what this code is trying to accomplish. What questions are you trying to answer with these lines? This will help you remember your thought process when you revisit your code and it will also help other readers better understand and critique your code.

**Comment by wickram** [comment]
Hi Caelana, Thanks for reviewing this. I did all the changes suggested by you and updated both the code and presentation again. Please review it and share your feedback
